import React from "react";
import type { Metadata } from "next";
import CalculatorHeader from "@/components/CalculatorHeader";
import FooterSection from "@/components/FooterSection";

export const metadata: Metadata = {
  title: "Terms & Conditions — Aspect Ratio Calculator",
  description:
    "Terms of service and commercial license terms for using the Free Aspect Ratio Calculator web application.",
  alternates: {
    canonical: "https://freeaspectratiocalculator.com/terms-and-conditions",
  },
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://freeaspectratiocalculator.com",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Terms & Conditions",
      item: "https://freeaspectratiocalculator.com/terms-and-conditions",
    },
  ],
};

export default function TermsAndConditionsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <div className="max-w-6xl mx-auto px-3 sm:px-6 lg:px-8 py-6">
        <CalculatorHeader />

        <article className="studio-card p-6 sm:p-10 space-y-6">
          <div className="border-b border-white/[0.08] pb-5">
            <span className="text-xs font-mono text-[#888888] uppercase tracking-wider block mb-1">
              Legal Agreement
            </span>
            <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-display-lg font-sans">
              Terms & Conditions.
            </h1>
            <p className="text-xs font-mono text-[#888888] mt-1">
              Last Updated: January 1, 2026
            </p>
          </div>

          <div className="space-y-4 text-sm leading-relaxed text-neutral-300 font-sans">
            <h2 className="text-base font-bold text-white font-sans">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using <strong>Aspect Ratio Calculator</strong>, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not access or use the application.
            </p>

            <h2 className="text-base font-bold text-white font-sans">
              2. Permitted Commercial & Personal Use
            </h2>
            <p>
              Our web application is provided 100% free of charge for both personal and commercial use. Designers, developers, agencies, and video editors are permitted to use calculations, scale tables, and exported code snippets in commercial software, web design projects, or media production without royalty fees.
            </p>

            <h2 className="text-base font-bold text-white font-sans">
              3. Open-Source Code Snippets (MIT License)
            </h2>
            <p>
              All developer code snippets generated by our application (including modern CSS <code className="font-mono text-white bg-[#171717] px-1.5 py-0.5 rounded">aspect-ratio</code> properties, Tailwind CSS utility classes, and SVG <code className="font-mono text-white bg-[#171717] px-1.5 py-0.5 rounded">viewBox</code> attributes) are licensed under the open-source MIT License.
            </p>

            <h2 className="text-base font-bold text-white font-sans">
              4. Intellectual Property
            </h2>
            <p>
              All branding, interface designs, logos, software logic, and custom components of the Aspect Ratio Calculator platform remain the intellectual property of the studio.
            </p>

            <h2 className="text-base font-bold text-white font-sans">
              5. Disclaimer of Warranties
            </h2>
            <p>
              The tool is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. While mathematical calculations use precise Greatest Common Divisor (GCD) algorithms, users are responsible for verifying final physical resolution specifications prior to high-volume commercial print production.
            </p>
          </div>
        </article>

        <FooterSection />
      </div>
    </>
  );
}
